name: Build and Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      # Step 3: Install dependencies using yarn
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build the project
        run: yarn build  # This will generate the dist/ folder or the output directory of your choice

      # Step 5: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          # Set the version dynamically or use the version from the tag
          VERSION=$(node -p "require('./package.json').version")
          yarn publish --new-version $VERSION --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionally: You can also upload built files as artifacts (if not using GitHub Packages for storage)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
